name: Mirror File

on: push
    
env:
  MIR: wss
  FILENAME: origin.7z
  URL: "http://transfer.mediatek.com/Detail/Download/File30009223656"
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Setup + download
         run: |
              sudo apt install aria2
              aria2c -x16 $URL
              
       - name: artifact
         uses: actions/upload-artifact@v2
         with:
          name: GMSExpress
          path: "*.zip"
