name: Mirror File

on: push
    
env:
  MIR: wss
  FILENAME: origin.7z
  URL: "https://mirrors.lolinet.com/firmware/moto/lake/official/RETAIL/LAKE_RETAIL_10_QPWS30.61-21-9_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml.zip"
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Setup + download
         run: |
              sudo apt install aria2
              aria2c -x16 $URL
              unzip *.zip
              
       - name: artifact
         uses: actions/upload-artifact@v2
         with:
          name: GMSExpress
          path: "gpt.bin"
