name: Mirror File

on: push
    
env:
  MIR: wss
  FILENAME: origin.7z
  URL: "https://the-eye.eu/public/MSDN/Office%202003/en_office_2003_std.iso"
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Setup + download
         run: |
              sudo apt install aria2
              aria2c -x16 --out=$FILENAME $URL
              
       - name: artifact
         uses: actions/upload-artifact@v2
         with:
          name: file
          path: "*.*"
