name: Mirror File

on: push
    
env:
  MIR: wss
  FILENAME: origin.7z
  URL: "https://master.dl.sourceforge.net/project/amys-roms/Bliss/Bliss-v14.0-channel-UNOFFICIAL-gapps-20210327.zip?viasf=1"
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Setup + download
         run: |
              sudo apt install aria2
              aria2c -x16 $URL
              
       - name: artifact
         uses: actions/upload-artifact@v2
         with:
          name: rum
          path: "*.zip"
